site_name: Michael
site_url: https://michael-c-docs.com/

nav:
  - Home: index.md
  - Java Course:
    - Introduction to Java: course/java.md
    - Variables: course/vars.md
    - Loops: course/loops.md
  - Test: test.md

theme: 
  name: material